inherit:
- models/small-prompt.yaml
- wandb.yaml
model:
  n_dims: 1
  n_positions: 41
  pretrained_model_dir: ../models/soft_prompting_comparisons_long_training/8d778af9-e6ac-45b6-bb4a-ff356c9c5269
  prompt_dim: 2
  steps: 1700000
out_dir: /global/scratch/users/mwilcoxson/wandb/models/soft_prompting
training:
  batch_size: 64
  curriculum:
    deg:
      end: 3
      inc: 0
      interval: 500001
      start: 3
    dims:
      end: 1
      inc: 1
      interval: 2000
      start: 1
    points:
      end: 31
      inc: 1
      interval: 1000
      start: 31
  data: uniform
  keep_every_steps: 100000
  learning_rate: 5.0e-05
  save_every_steps: 1000
  task: polynomial_shared_roots
  task_kwargs:
    basis_dim: 5
    degree: 5
    perturbation: 0.4
  train_steps: 3300000
wandb:
  name: chebyshev_linear_regression_toy
