inherit:
- models/small-prompt.yaml
- wandb.yaml
model:
  n_dims: 1
  n_positions: 131
  pretrained_model_dir: /global/scratch/users/mwilcoxson/wandb/models/kernel_linear_regression_2/c8a12fe0-218e-4fdc-a29b-6eab36983e39
  prompt_dim: 70
out_dir: /global/scratch/users/mwilcoxson/wandb/models/soft_prompting_long_lengths
training:
  batch_size: 64
  curriculum:
    deg:
      end: 3
      inc: 0
      interval: 500001
      start: 3
    dims:
      end: 1
      inc: 1
      interval: 2000
      start: 1
    points:
      end: 31
      inc: 1
      interval: 1000
      start: 31
  data: uniform
  keep_every_steps: 100000
  learning_rate: 5.0e-05
  save_every_steps: 1000
  task: chebyshev_kernel_linear_regression
  task_kwargs:
    basis_dim: 5
    fixed_coeffs: 0
    highest_degree: 5
    lowest_degree: 5
    scale: 1.0
  train_steps: 1000000
wandb:
  name: chebyshev_linear_regression_toy
