inherit:
- models/small-prompt.yaml
- wandb.yaml
model:
  n_dims: 1
  n_positions: 131
  positional_encodings: true
  pretrained_model_dir: /home/mwilcoxson/Code/CS182Project/models/kernel_linear_regression/131-context-w-positional-embeddings
  prompt_dim: 50
out_dir:  /home/mwilcoxson/Code/CS182Project/models/soft_prompting_noise
training:
  batch_size: 64
  curriculum:
    deg:
      end: 3
      inc: 0
      interval: 500001
      start: 3
    dims:
      end: 1
      inc: 1
      interval: 2000
      start: 1
    points:
      end: 31
      inc: 1
      interval: 1000
      start: 31
  data: uniform
  keep_every_steps: 100000
  learning_rate: 5.0e-05
  resume_id: prompt8
  save_every_steps: 1000
  task: chebyshev_kernel_linear_regression
  task_kwargs:
    basis_dim: 5
    fixed_coeffs: 2
    highest_degree: 5
    lowest_degree: 5
    scale: 1.0
  train_steps: 2000000
wandb:
  name: prompt8
