inherit: 
    - models/standard.yaml
    - wandb.yaml

model:
    n_dims: 1
    n_positions: 131
    positional_encoding: true

training:
    task: kernel_linear_regression
    data: uniform
    resume_id: base_model_noisy
    # task_kwargs: {"basis_dim": 11, "different_degrees": True, "lowest_degree": 1, "highest_degree": 11}
    task_kwargs: {"basis_dim": 11, "different_degrees": True, "lowest_degree": 1, "highest_degree": 11}

    num_tasks: null
    num_training_examples: null
    noise_variance: 0.2

    batch_size: 64
    learning_rate: 0.00005
    save_every_steps: 1000
    keep_every_steps: 100000
    train_steps: 5000001
    curriculum:
        dims:
            start: 1
            end: 1
            inc: 1
            interval: 2000
        points:
            start: 5
            end: 131
            inc: 1
            interval: 1000
        deg: 
            start: 11
            end: 11
            inc: 0
            interval: 500001

out_dir: ../models/polynomial_regression

wandb:
    name: "chebyshev_regression_noisy"