inherit: 
    - models/small.yaml
    - wandb.yaml

model:
    n_dims: 1
    n_positions: 131

training:
    task: mixed_sliced_chebyshev
    data: uniform
    resume_id: mixed_sliced_chebychev

    num_tasks: null
    num_training_examples: null
    noise_variance: 0

    batch_size: 64
    learning_rate: 0.00005
    save_every_steps: 1000
    keep_every_steps: 100000
    train_steps: 1400001
    curriculum:
        dims:
            start: 1
            end: 1
            inc: 1
            interval: 2000
        points:
            start: 31
            end: 31
            inc: 1
            interval: 1000
        deg: 
            start: 5
            end: 5
            inc: 0
            interval: 500001

out_dir: ../models/mixed_sliced_chebychev

wandb:
    name: "mixed_sliced_chebychev"