inherit: 
    - models/small-prompt.yaml
    - wandb.yaml

model:
    n_dims: 1
    n_positions: 131
    prompt_dim: 100
    pretrained_model_dir: ../models/mixed_sliced_chebychev/unknown

training:
    task: chebyshev_shared_roots
    data: uniform
    resume_id: chebyshev_shared_roots_prompt

    num_tasks: null
    num_training_examples: null
    noise_variance: 0.0
    task_kwargs: {}

    batch_size: 64
    learning_rate: 0.00005
    save_every_steps: 1000
    keep_every_steps: 100000
    train_steps: 300001
    curriculum:
        dims:
            start: 1
            end: 1
            inc: 1
            interval: 2000
        points:
            start: 31
            end: 31
            inc: 1
            interval: 1000
        deg: 
            start: 5
            end: 5
            inc: 0
            interval: 500001

out_dir: ../models/chebyshev_shared_roots_prompt

wandb:
    name: "chebyshev_shared_roots_prompt"