inherit: 
    - models/standard.yaml
    - wandb.yaml

model:
    n_dims: 1
    n_positions: 41

training:
    task: kernel_linear_regression
    data: gaussian
    # task_kwargs: {"basis_dim": 11, "different_degrees": True, "lowest_degree": 1, "highest_degree": 11}
    task_kwargs: {"basis_dim": 11, "different_degrees": True, "lowest_degree": 1}

    batch_size: 64
    learning_rate: 0.00005
    save_every_steps: 1000
    keep_every_steps: 100000
    train_steps: 5000001
    curriculum:
        dims:
            start: 1
            end: 1
            inc: 1
            interval: 2000
        points:
            start: 5
            end: 41
            inc: 1
            interval: 1000
        deg: 
            start: 11
            end: 11
            inc: 0
            interval: 500001

out_dir: ../models/kernel_linear_regression

wandb:
    name: "chebyshev_linear_regression_toy"
