inherit: 
    - models/small.yaml
    - wandb.yaml

model:
    n_dims: 1
    n_positions: 131
    pretrained_model_dir: ../models/kernel_linear_regression/c0fffde9-ee15-429c-a1f1-e89985f35037
    steps: 1400000

training:
    task: chebyshev_kernel_linear_regression
    data: uniform
    # task_kwargs: {"basis_dim": 11, "different_degrees": True, "lowest_degree": 1, "highest_degree": 11}
    task_kwargs: 
        highest_degree: 11
        basis_dim: 11
        different_degrees: True
        lowest_degree: 1
        fixed_coeffs: 0
        scale: 1.0
    batch_size: 64
    learning_rate: 0.00005
    save_every_steps: 1000
    keep_every_steps: 100000
    train_steps: 1600000
    curriculum:
        dims:
            start: 1
            end: 1
            inc: 1
            interval: 2000
        points:
            start: 5
            end: 131
            inc: 1
            interval: 1000
        deg: 
            start: 11
            end: 11
            inc: 0
            interval: 500001

out_dir: ../models/kernel_linear_regression_2

wandb:
    name: "chebyshev_linear_regression_toy"
