inherit: 
    - models/standard.yaml
    - wandb.yaml

model:
    n_dims: 5
    n_positions: 41

training:
    task: kernel_linear_regression
    data: gaussian
    task_kwargs: {"basis_dim": 4}
    batch_size: 64
    learning_rate: 0.0001
    save_every_steps: 1000
    keep_every_steps: 100000
    train_steps: 500001
    curriculum:
        dims:
            start: 5
            end: 5
            inc: 1
            interval: 2000
        points:
            start: 11
            end: 41
            inc: 2
            interval: 2000

out_dir: ../models/kernel_linear_regression

wandb:
    name: "kernel_linear_regression_toy"
